// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fileDataEvent.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

/**
 * Protobuf enum {@code ClassType}
 */
public enum ClassType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INTERFACE = 0;</code>
   */
  INTERFACE(0),
  /**
   * <code>ABSTRACT_CLASS = 1;</code>
   */
  ABSTRACT_CLASS(1),
  /**
   * <code>CLASS = 2;</code>
   */
  CLASS(2),
  /**
   * <code>ENUM = 3;</code>
   */
  ENUM(3),
  /**
   * <code>ANONYMOUS_CLASS = 4;</code>
   */
  ANONYMOUS_CLASS(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INTERFACE = 0;</code>
   */
  public static final int INTERFACE_VALUE = 0;
  /**
   * <code>ABSTRACT_CLASS = 1;</code>
   */
  public static final int ABSTRACT_CLASS_VALUE = 1;
  /**
   * <code>CLASS = 2;</code>
   */
  public static final int CLASS_VALUE = 2;
  /**
   * <code>ENUM = 3;</code>
   */
  public static final int ENUM_VALUE = 3;
  /**
   * <code>ANONYMOUS_CLASS = 4;</code>
   */
  public static final int ANONYMOUS_CLASS_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClassType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ClassType forNumber(int value) {
    switch (value) {
      case 0: return INTERFACE;
      case 1: return ABSTRACT_CLASS;
      case 2: return CLASS;
      case 3: return ENUM;
      case 4: return ANONYMOUS_CLASS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClassType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClassType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClassType>() {
          public ClassType findValueByNumber(int number) {
            return ClassType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.explorviz.code.proto.FileDataEvent.getDescriptor().getEnumTypes().get(0);
  }

  private static final ClassType[] VALUES = values();

  public static ClassType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ClassType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ClassType)
}

