// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/commitReport.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

public final class CommitReport {
  private CommitReport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitReportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitReportData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileMetricData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileMetricData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/commitReport.proto\032\033google/proto" +
      "buf/empty.proto\"\341\001\n\020CommitReportData\022\020\n\010" +
      "commitID\030\001 \001(\t\022\026\n\016parentCommitID\030\002 \001(\t\022\022" +
      "\n\nbranchName\030\003 \001(\t\022\r\n\005files\030\004 \003(\t\022\020\n\010mod" +
      "ified\030\005 \003(\t\022\017\n\007deleted\030\006 \003(\t\022\r\n\005added\030\007 " +
      "\003(\t\022#\n\nfileMetric\030\010 \003(\0132\017.FileMetricData" +
      "\022\021\n\tcommitTag\030\t \001(\t\022\026\n\016landscapeToken\030\n " +
      "\001(\t\"f\n\016FileMetricData\022\020\n\010fileName\030\001 \001(\t\022" +
      "\013\n\003loc\030\002 \001(\005\022\034\n\024cyclomaticComplexity\030\003 \001" +
      "(\005\022\027\n\017numberOfMethods\030\004 \001(\0052V\n\023CommitRep" +
      "ortService\022?\n\020sendCommitReport\022\021.CommitR" +
      "eportData\032\026.google.protobuf.Empty\"\000B*\n\030n" +
      "et.explorviz.code.protoB\014CommitReportP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_CommitReportData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommitReportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitReportData_descriptor,
        new java.lang.String[] { "CommitID", "ParentCommitID", "BranchName", "Files", "Modified", "Deleted", "Added", "FileMetric", "CommitTag", "LandscapeToken", });
    internal_static_FileMetricData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileMetricData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileMetricData_descriptor,
        new java.lang.String[] { "FileName", "Loc", "CyclomaticComplexity", "NumberOfMethods", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
