// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/commitReport.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

/**
 * Protobuf type {@code CommitReportData}
 */
public final class CommitReportData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CommitReportData)
    CommitReportDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommitReportData.newBuilder() to construct.
  private CommitReportData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommitReportData() {
    commitID_ = "";
    parentCommitID_ = "";
    branchName_ = "";
    files_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    modified_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    deleted_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    added_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    fileMetric_ = java.util.Collections.emptyList();
    commitTag_ = "";
    landscapeToken_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommitReportData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.explorviz.code.proto.CommitReport.internal_static_CommitReportData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.explorviz.code.proto.CommitReport.internal_static_CommitReportData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.explorviz.code.proto.CommitReportData.class, net.explorviz.code.proto.CommitReportData.Builder.class);
  }

  public static final int COMMITID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commitID_ = "";
  /**
   * <code>string commitID = 1;</code>
   * @return The commitID.
   */
  @java.lang.Override
  public java.lang.String getCommitID() {
    java.lang.Object ref = commitID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commitID_ = s;
      return s;
    }
  }
  /**
   * <code>string commitID = 1;</code>
   * @return The bytes for commitID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommitIDBytes() {
    java.lang.Object ref = commitID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commitID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTCOMMITID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object parentCommitID_ = "";
  /**
   * <code>string parentCommitID = 2;</code>
   * @return The parentCommitID.
   */
  @java.lang.Override
  public java.lang.String getParentCommitID() {
    java.lang.Object ref = parentCommitID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentCommitID_ = s;
      return s;
    }
  }
  /**
   * <code>string parentCommitID = 2;</code>
   * @return The bytes for parentCommitID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentCommitIDBytes() {
    java.lang.Object ref = parentCommitID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentCommitID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRANCHNAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object branchName_ = "";
  /**
   * <code>string branchName = 3;</code>
   * @return The branchName.
   */
  @java.lang.Override
  public java.lang.String getBranchName() {
    java.lang.Object ref = branchName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      branchName_ = s;
      return s;
    }
  }
  /**
   * <code>string branchName = 3;</code>
   * @return The bytes for branchName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBranchNameBytes() {
    java.lang.Object ref = branchName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      branchName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList files_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string files = 4;</code>
   * @return A list containing the files.
   */
  public com.google.protobuf.ProtocolStringList
      getFilesList() {
    return files_;
  }
  /**
   * <code>repeated string files = 4;</code>
   * @return The count of files.
   */
  public int getFilesCount() {
    return files_.size();
  }
  /**
   * <code>repeated string files = 4;</code>
   * @param index The index of the element to return.
   * @return The files at the given index.
   */
  public java.lang.String getFiles(int index) {
    return files_.get(index);
  }
  /**
   * <code>repeated string files = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the files at the given index.
   */
  public com.google.protobuf.ByteString
      getFilesBytes(int index) {
    return files_.getByteString(index);
  }

  public static final int MODIFIED_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList modified_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string modified = 5;</code>
   * @return A list containing the modified.
   */
  public com.google.protobuf.ProtocolStringList
      getModifiedList() {
    return modified_;
  }
  /**
   * <code>repeated string modified = 5;</code>
   * @return The count of modified.
   */
  public int getModifiedCount() {
    return modified_.size();
  }
  /**
   * <code>repeated string modified = 5;</code>
   * @param index The index of the element to return.
   * @return The modified at the given index.
   */
  public java.lang.String getModified(int index) {
    return modified_.get(index);
  }
  /**
   * <code>repeated string modified = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the modified at the given index.
   */
  public com.google.protobuf.ByteString
      getModifiedBytes(int index) {
    return modified_.getByteString(index);
  }

  public static final int DELETED_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList deleted_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string deleted = 6;</code>
   * @return A list containing the deleted.
   */
  public com.google.protobuf.ProtocolStringList
      getDeletedList() {
    return deleted_;
  }
  /**
   * <code>repeated string deleted = 6;</code>
   * @return The count of deleted.
   */
  public int getDeletedCount() {
    return deleted_.size();
  }
  /**
   * <code>repeated string deleted = 6;</code>
   * @param index The index of the element to return.
   * @return The deleted at the given index.
   */
  public java.lang.String getDeleted(int index) {
    return deleted_.get(index);
  }
  /**
   * <code>repeated string deleted = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the deleted at the given index.
   */
  public com.google.protobuf.ByteString
      getDeletedBytes(int index) {
    return deleted_.getByteString(index);
  }

  public static final int ADDED_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList added_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string added = 7;</code>
   * @return A list containing the added.
   */
  public com.google.protobuf.ProtocolStringList
      getAddedList() {
    return added_;
  }
  /**
   * <code>repeated string added = 7;</code>
   * @return The count of added.
   */
  public int getAddedCount() {
    return added_.size();
  }
  /**
   * <code>repeated string added = 7;</code>
   * @param index The index of the element to return.
   * @return The added at the given index.
   */
  public java.lang.String getAdded(int index) {
    return added_.get(index);
  }
  /**
   * <code>repeated string added = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the added at the given index.
   */
  public com.google.protobuf.ByteString
      getAddedBytes(int index) {
    return added_.getByteString(index);
  }

  public static final int FILEMETRIC_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<net.explorviz.code.proto.FileMetricData> fileMetric_;
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  @java.lang.Override
  public java.util.List<net.explorviz.code.proto.FileMetricData> getFileMetricList() {
    return fileMetric_;
  }
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.explorviz.code.proto.FileMetricDataOrBuilder> 
      getFileMetricOrBuilderList() {
    return fileMetric_;
  }
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  @java.lang.Override
  public int getFileMetricCount() {
    return fileMetric_.size();
  }
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  @java.lang.Override
  public net.explorviz.code.proto.FileMetricData getFileMetric(int index) {
    return fileMetric_.get(index);
  }
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  @java.lang.Override
  public net.explorviz.code.proto.FileMetricDataOrBuilder getFileMetricOrBuilder(
      int index) {
    return fileMetric_.get(index);
  }

  public static final int COMMITTAG_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commitTag_ = "";
  /**
   * <code>string commitTag = 9;</code>
   * @return The commitTag.
   */
  @java.lang.Override
  public java.lang.String getCommitTag() {
    java.lang.Object ref = commitTag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commitTag_ = s;
      return s;
    }
  }
  /**
   * <code>string commitTag = 9;</code>
   * @return The bytes for commitTag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommitTagBytes() {
    java.lang.Object ref = commitTag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commitTag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANDSCAPETOKEN_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object landscapeToken_ = "";
  /**
   * <code>string landscapeToken = 10;</code>
   * @return The landscapeToken.
   */
  @java.lang.Override
  public java.lang.String getLandscapeToken() {
    java.lang.Object ref = landscapeToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      landscapeToken_ = s;
      return s;
    }
  }
  /**
   * <code>string landscapeToken = 10;</code>
   * @return The bytes for landscapeToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLandscapeTokenBytes() {
    java.lang.Object ref = landscapeToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      landscapeToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commitID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentCommitID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, parentCommitID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(branchName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, branchName_);
    }
    for (int i = 0; i < files_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, files_.getRaw(i));
    }
    for (int i = 0; i < modified_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, modified_.getRaw(i));
    }
    for (int i = 0; i < deleted_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deleted_.getRaw(i));
    }
    for (int i = 0; i < added_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, added_.getRaw(i));
    }
    for (int i = 0; i < fileMetric_.size(); i++) {
      output.writeMessage(8, fileMetric_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitTag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, commitTag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(landscapeToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, landscapeToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commitID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(parentCommitID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, parentCommitID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(branchName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, branchName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < files_.size(); i++) {
        dataSize += computeStringSizeNoTag(files_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFilesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < modified_.size(); i++) {
        dataSize += computeStringSizeNoTag(modified_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getModifiedList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < deleted_.size(); i++) {
        dataSize += computeStringSizeNoTag(deleted_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDeletedList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < added_.size(); i++) {
        dataSize += computeStringSizeNoTag(added_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAddedList().size();
    }
    for (int i = 0; i < fileMetric_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, fileMetric_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitTag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, commitTag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(landscapeToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, landscapeToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.explorviz.code.proto.CommitReportData)) {
      return super.equals(obj);
    }
    net.explorviz.code.proto.CommitReportData other = (net.explorviz.code.proto.CommitReportData) obj;

    if (!getCommitID()
        .equals(other.getCommitID())) return false;
    if (!getParentCommitID()
        .equals(other.getParentCommitID())) return false;
    if (!getBranchName()
        .equals(other.getBranchName())) return false;
    if (!getFilesList()
        .equals(other.getFilesList())) return false;
    if (!getModifiedList()
        .equals(other.getModifiedList())) return false;
    if (!getDeletedList()
        .equals(other.getDeletedList())) return false;
    if (!getAddedList()
        .equals(other.getAddedList())) return false;
    if (!getFileMetricList()
        .equals(other.getFileMetricList())) return false;
    if (!getCommitTag()
        .equals(other.getCommitTag())) return false;
    if (!getLandscapeToken()
        .equals(other.getLandscapeToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMITID_FIELD_NUMBER;
    hash = (53 * hash) + getCommitID().hashCode();
    hash = (37 * hash) + PARENTCOMMITID_FIELD_NUMBER;
    hash = (53 * hash) + getParentCommitID().hashCode();
    hash = (37 * hash) + BRANCHNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBranchName().hashCode();
    if (getFilesCount() > 0) {
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + getFilesList().hashCode();
    }
    if (getModifiedCount() > 0) {
      hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
      hash = (53 * hash) + getModifiedList().hashCode();
    }
    if (getDeletedCount() > 0) {
      hash = (37 * hash) + DELETED_FIELD_NUMBER;
      hash = (53 * hash) + getDeletedList().hashCode();
    }
    if (getAddedCount() > 0) {
      hash = (37 * hash) + ADDED_FIELD_NUMBER;
      hash = (53 * hash) + getAddedList().hashCode();
    }
    if (getFileMetricCount() > 0) {
      hash = (37 * hash) + FILEMETRIC_FIELD_NUMBER;
      hash = (53 * hash) + getFileMetricList().hashCode();
    }
    hash = (37 * hash) + COMMITTAG_FIELD_NUMBER;
    hash = (53 * hash) + getCommitTag().hashCode();
    hash = (37 * hash) + LANDSCAPETOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getLandscapeToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.explorviz.code.proto.CommitReportData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.explorviz.code.proto.CommitReportData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.explorviz.code.proto.CommitReportData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.CommitReportData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.explorviz.code.proto.CommitReportData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CommitReportData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CommitReportData)
      net.explorviz.code.proto.CommitReportDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.explorviz.code.proto.CommitReport.internal_static_CommitReportData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.explorviz.code.proto.CommitReport.internal_static_CommitReportData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.explorviz.code.proto.CommitReportData.class, net.explorviz.code.proto.CommitReportData.Builder.class);
    }

    // Construct using net.explorviz.code.proto.CommitReportData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commitID_ = "";
      parentCommitID_ = "";
      branchName_ = "";
      files_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      modified_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      deleted_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      added_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (fileMetricBuilder_ == null) {
        fileMetric_ = java.util.Collections.emptyList();
      } else {
        fileMetric_ = null;
        fileMetricBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      commitTag_ = "";
      landscapeToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.explorviz.code.proto.CommitReport.internal_static_CommitReportData_descriptor;
    }

    @java.lang.Override
    public net.explorviz.code.proto.CommitReportData getDefaultInstanceForType() {
      return net.explorviz.code.proto.CommitReportData.getDefaultInstance();
    }

    @java.lang.Override
    public net.explorviz.code.proto.CommitReportData build() {
      net.explorviz.code.proto.CommitReportData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.explorviz.code.proto.CommitReportData buildPartial() {
      net.explorviz.code.proto.CommitReportData result = new net.explorviz.code.proto.CommitReportData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(net.explorviz.code.proto.CommitReportData result) {
      if (fileMetricBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          fileMetric_ = java.util.Collections.unmodifiableList(fileMetric_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.fileMetric_ = fileMetric_;
      } else {
        result.fileMetric_ = fileMetricBuilder_.build();
      }
    }

    private void buildPartial0(net.explorviz.code.proto.CommitReportData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commitID_ = commitID_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.parentCommitID_ = parentCommitID_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.branchName_ = branchName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        files_.makeImmutable();
        result.files_ = files_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        modified_.makeImmutable();
        result.modified_ = modified_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        deleted_.makeImmutable();
        result.deleted_ = deleted_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        added_.makeImmutable();
        result.added_ = added_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.commitTag_ = commitTag_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.landscapeToken_ = landscapeToken_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.explorviz.code.proto.CommitReportData) {
        return mergeFrom((net.explorviz.code.proto.CommitReportData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.explorviz.code.proto.CommitReportData other) {
      if (other == net.explorviz.code.proto.CommitReportData.getDefaultInstance()) return this;
      if (!other.getCommitID().isEmpty()) {
        commitID_ = other.commitID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getParentCommitID().isEmpty()) {
        parentCommitID_ = other.parentCommitID_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBranchName().isEmpty()) {
        branchName_ = other.branchName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.files_.isEmpty()) {
        if (files_.isEmpty()) {
          files_ = other.files_;
          bitField0_ |= 0x00000008;
        } else {
          ensureFilesIsMutable();
          files_.addAll(other.files_);
        }
        onChanged();
      }
      if (!other.modified_.isEmpty()) {
        if (modified_.isEmpty()) {
          modified_ = other.modified_;
          bitField0_ |= 0x00000010;
        } else {
          ensureModifiedIsMutable();
          modified_.addAll(other.modified_);
        }
        onChanged();
      }
      if (!other.deleted_.isEmpty()) {
        if (deleted_.isEmpty()) {
          deleted_ = other.deleted_;
          bitField0_ |= 0x00000020;
        } else {
          ensureDeletedIsMutable();
          deleted_.addAll(other.deleted_);
        }
        onChanged();
      }
      if (!other.added_.isEmpty()) {
        if (added_.isEmpty()) {
          added_ = other.added_;
          bitField0_ |= 0x00000040;
        } else {
          ensureAddedIsMutable();
          added_.addAll(other.added_);
        }
        onChanged();
      }
      if (fileMetricBuilder_ == null) {
        if (!other.fileMetric_.isEmpty()) {
          if (fileMetric_.isEmpty()) {
            fileMetric_ = other.fileMetric_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureFileMetricIsMutable();
            fileMetric_.addAll(other.fileMetric_);
          }
          onChanged();
        }
      } else {
        if (!other.fileMetric_.isEmpty()) {
          if (fileMetricBuilder_.isEmpty()) {
            fileMetricBuilder_.dispose();
            fileMetricBuilder_ = null;
            fileMetric_ = other.fileMetric_;
            bitField0_ = (bitField0_ & ~0x00000080);
            fileMetricBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFileMetricFieldBuilder() : null;
          } else {
            fileMetricBuilder_.addAllMessages(other.fileMetric_);
          }
        }
      }
      if (!other.getCommitTag().isEmpty()) {
        commitTag_ = other.commitTag_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getLandscapeToken().isEmpty()) {
        landscapeToken_ = other.landscapeToken_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commitID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              parentCommitID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              branchName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFilesIsMutable();
              files_.add(s);
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureModifiedIsMutable();
              modified_.add(s);
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDeletedIsMutable();
              deleted_.add(s);
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAddedIsMutable();
              added_.add(s);
              break;
            } // case 58
            case 66: {
              net.explorviz.code.proto.FileMetricData m =
                  input.readMessage(
                      net.explorviz.code.proto.FileMetricData.parser(),
                      extensionRegistry);
              if (fileMetricBuilder_ == null) {
                ensureFileMetricIsMutable();
                fileMetric_.add(m);
              } else {
                fileMetricBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              commitTag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              landscapeToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object commitID_ = "";
    /**
     * <code>string commitID = 1;</code>
     * @return The commitID.
     */
    public java.lang.String getCommitID() {
      java.lang.Object ref = commitID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commitID = 1;</code>
     * @return The bytes for commitID.
     */
    public com.google.protobuf.ByteString
        getCommitIDBytes() {
      java.lang.Object ref = commitID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commitID = 1;</code>
     * @param value The commitID to set.
     * @return This builder for chaining.
     */
    public Builder setCommitID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commitID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string commitID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitID() {
      commitID_ = getDefaultInstance().getCommitID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string commitID = 1;</code>
     * @param value The bytes for commitID to set.
     * @return This builder for chaining.
     */
    public Builder setCommitIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commitID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object parentCommitID_ = "";
    /**
     * <code>string parentCommitID = 2;</code>
     * @return The parentCommitID.
     */
    public java.lang.String getParentCommitID() {
      java.lang.Object ref = parentCommitID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentCommitID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parentCommitID = 2;</code>
     * @return The bytes for parentCommitID.
     */
    public com.google.protobuf.ByteString
        getParentCommitIDBytes() {
      java.lang.Object ref = parentCommitID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentCommitID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parentCommitID = 2;</code>
     * @param value The parentCommitID to set.
     * @return This builder for chaining.
     */
    public Builder setParentCommitID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      parentCommitID_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string parentCommitID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentCommitID() {
      parentCommitID_ = getDefaultInstance().getParentCommitID();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string parentCommitID = 2;</code>
     * @param value The bytes for parentCommitID to set.
     * @return This builder for chaining.
     */
    public Builder setParentCommitIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      parentCommitID_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object branchName_ = "";
    /**
     * <code>string branchName = 3;</code>
     * @return The branchName.
     */
    public java.lang.String getBranchName() {
      java.lang.Object ref = branchName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        branchName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string branchName = 3;</code>
     * @return The bytes for branchName.
     */
    public com.google.protobuf.ByteString
        getBranchNameBytes() {
      java.lang.Object ref = branchName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        branchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string branchName = 3;</code>
     * @param value The branchName to set.
     * @return This builder for chaining.
     */
    public Builder setBranchName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      branchName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string branchName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBranchName() {
      branchName_ = getDefaultInstance().getBranchName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string branchName = 3;</code>
     * @param value The bytes for branchName to set.
     * @return This builder for chaining.
     */
    public Builder setBranchNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      branchName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList files_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFilesIsMutable() {
      if (!files_.isModifiable()) {
        files_ = new com.google.protobuf.LazyStringArrayList(files_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string files = 4;</code>
     * @return A list containing the files.
     */
    public com.google.protobuf.ProtocolStringList
        getFilesList() {
      files_.makeImmutable();
      return files_;
    }
    /**
     * <code>repeated string files = 4;</code>
     * @return The count of files.
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <code>repeated string files = 4;</code>
     * @param index The index of the element to return.
     * @return The files at the given index.
     */
    public java.lang.String getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <code>repeated string files = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the files at the given index.
     */
    public com.google.protobuf.ByteString
        getFilesBytes(int index) {
      return files_.getByteString(index);
    }
    /**
     * <code>repeated string files = 4;</code>
     * @param index The index to set the value at.
     * @param value The files to set.
     * @return This builder for chaining.
     */
    public Builder setFiles(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilesIsMutable();
      files_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 4;</code>
     * @param value The files to add.
     * @return This builder for chaining.
     */
    public Builder addFiles(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilesIsMutable();
      files_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 4;</code>
     * @param values The files to add.
     * @return This builder for chaining.
     */
    public Builder addAllFiles(
        java.lang.Iterable<java.lang.String> values) {
      ensureFilesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, files_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFiles() {
      files_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string files = 4;</code>
     * @param value The bytes of the files to add.
     * @return This builder for chaining.
     */
    public Builder addFilesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFilesIsMutable();
      files_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList modified_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureModifiedIsMutable() {
      if (!modified_.isModifiable()) {
        modified_ = new com.google.protobuf.LazyStringArrayList(modified_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @return A list containing the modified.
     */
    public com.google.protobuf.ProtocolStringList
        getModifiedList() {
      modified_.makeImmutable();
      return modified_;
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @return The count of modified.
     */
    public int getModifiedCount() {
      return modified_.size();
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @param index The index of the element to return.
     * @return The modified at the given index.
     */
    public java.lang.String getModified(int index) {
      return modified_.get(index);
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the modified at the given index.
     */
    public com.google.protobuf.ByteString
        getModifiedBytes(int index) {
      return modified_.getByteString(index);
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @param index The index to set the value at.
     * @param value The modified to set.
     * @return This builder for chaining.
     */
    public Builder setModified(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureModifiedIsMutable();
      modified_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @param value The modified to add.
     * @return This builder for chaining.
     */
    public Builder addModified(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureModifiedIsMutable();
      modified_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @param values The modified to add.
     * @return This builder for chaining.
     */
    public Builder addAllModified(
        java.lang.Iterable<java.lang.String> values) {
      ensureModifiedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, modified_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearModified() {
      modified_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modified = 5;</code>
     * @param value The bytes of the modified to add.
     * @return This builder for chaining.
     */
    public Builder addModifiedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureModifiedIsMutable();
      modified_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList deleted_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDeletedIsMutable() {
      if (!deleted_.isModifiable()) {
        deleted_ = new com.google.protobuf.LazyStringArrayList(deleted_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @return A list containing the deleted.
     */
    public com.google.protobuf.ProtocolStringList
        getDeletedList() {
      deleted_.makeImmutable();
      return deleted_;
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @return The count of deleted.
     */
    public int getDeletedCount() {
      return deleted_.size();
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @param index The index of the element to return.
     * @return The deleted at the given index.
     */
    public java.lang.String getDeleted(int index) {
      return deleted_.get(index);
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the deleted at the given index.
     */
    public com.google.protobuf.ByteString
        getDeletedBytes(int index) {
      return deleted_.getByteString(index);
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @param index The index to set the value at.
     * @param value The deleted to set.
     * @return This builder for chaining.
     */
    public Builder setDeleted(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDeletedIsMutable();
      deleted_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @param value The deleted to add.
     * @return This builder for chaining.
     */
    public Builder addDeleted(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDeletedIsMutable();
      deleted_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @param values The deleted to add.
     * @return This builder for chaining.
     */
    public Builder addAllDeleted(
        java.lang.Iterable<java.lang.String> values) {
      ensureDeletedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, deleted_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeleted() {
      deleted_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string deleted = 6;</code>
     * @param value The bytes of the deleted to add.
     * @return This builder for chaining.
     */
    public Builder addDeletedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDeletedIsMutable();
      deleted_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList added_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAddedIsMutable() {
      if (!added_.isModifiable()) {
        added_ = new com.google.protobuf.LazyStringArrayList(added_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <code>repeated string added = 7;</code>
     * @return A list containing the added.
     */
    public com.google.protobuf.ProtocolStringList
        getAddedList() {
      added_.makeImmutable();
      return added_;
    }
    /**
     * <code>repeated string added = 7;</code>
     * @return The count of added.
     */
    public int getAddedCount() {
      return added_.size();
    }
    /**
     * <code>repeated string added = 7;</code>
     * @param index The index of the element to return.
     * @return The added at the given index.
     */
    public java.lang.String getAdded(int index) {
      return added_.get(index);
    }
    /**
     * <code>repeated string added = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the added at the given index.
     */
    public com.google.protobuf.ByteString
        getAddedBytes(int index) {
      return added_.getByteString(index);
    }
    /**
     * <code>repeated string added = 7;</code>
     * @param index The index to set the value at.
     * @param value The added to set.
     * @return This builder for chaining.
     */
    public Builder setAdded(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAddedIsMutable();
      added_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string added = 7;</code>
     * @param value The added to add.
     * @return This builder for chaining.
     */
    public Builder addAdded(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAddedIsMutable();
      added_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string added = 7;</code>
     * @param values The added to add.
     * @return This builder for chaining.
     */
    public Builder addAllAdded(
        java.lang.Iterable<java.lang.String> values) {
      ensureAddedIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, added_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string added = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdded() {
      added_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string added = 7;</code>
     * @param value The bytes of the added to add.
     * @return This builder for chaining.
     */
    public Builder addAddedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAddedIsMutable();
      added_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.util.List<net.explorviz.code.proto.FileMetricData> fileMetric_ =
      java.util.Collections.emptyList();
    private void ensureFileMetricIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        fileMetric_ = new java.util.ArrayList<net.explorviz.code.proto.FileMetricData>(fileMetric_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.explorviz.code.proto.FileMetricData, net.explorviz.code.proto.FileMetricData.Builder, net.explorviz.code.proto.FileMetricDataOrBuilder> fileMetricBuilder_;

    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public java.util.List<net.explorviz.code.proto.FileMetricData> getFileMetricList() {
      if (fileMetricBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fileMetric_);
      } else {
        return fileMetricBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public int getFileMetricCount() {
      if (fileMetricBuilder_ == null) {
        return fileMetric_.size();
      } else {
        return fileMetricBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public net.explorviz.code.proto.FileMetricData getFileMetric(int index) {
      if (fileMetricBuilder_ == null) {
        return fileMetric_.get(index);
      } else {
        return fileMetricBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder setFileMetric(
        int index, net.explorviz.code.proto.FileMetricData value) {
      if (fileMetricBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileMetricIsMutable();
        fileMetric_.set(index, value);
        onChanged();
      } else {
        fileMetricBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder setFileMetric(
        int index, net.explorviz.code.proto.FileMetricData.Builder builderForValue) {
      if (fileMetricBuilder_ == null) {
        ensureFileMetricIsMutable();
        fileMetric_.set(index, builderForValue.build());
        onChanged();
      } else {
        fileMetricBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder addFileMetric(net.explorviz.code.proto.FileMetricData value) {
      if (fileMetricBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileMetricIsMutable();
        fileMetric_.add(value);
        onChanged();
      } else {
        fileMetricBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder addFileMetric(
        int index, net.explorviz.code.proto.FileMetricData value) {
      if (fileMetricBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileMetricIsMutable();
        fileMetric_.add(index, value);
        onChanged();
      } else {
        fileMetricBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder addFileMetric(
        net.explorviz.code.proto.FileMetricData.Builder builderForValue) {
      if (fileMetricBuilder_ == null) {
        ensureFileMetricIsMutable();
        fileMetric_.add(builderForValue.build());
        onChanged();
      } else {
        fileMetricBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder addFileMetric(
        int index, net.explorviz.code.proto.FileMetricData.Builder builderForValue) {
      if (fileMetricBuilder_ == null) {
        ensureFileMetricIsMutable();
        fileMetric_.add(index, builderForValue.build());
        onChanged();
      } else {
        fileMetricBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder addAllFileMetric(
        java.lang.Iterable<? extends net.explorviz.code.proto.FileMetricData> values) {
      if (fileMetricBuilder_ == null) {
        ensureFileMetricIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fileMetric_);
        onChanged();
      } else {
        fileMetricBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder clearFileMetric() {
      if (fileMetricBuilder_ == null) {
        fileMetric_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        fileMetricBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public Builder removeFileMetric(int index) {
      if (fileMetricBuilder_ == null) {
        ensureFileMetricIsMutable();
        fileMetric_.remove(index);
        onChanged();
      } else {
        fileMetricBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public net.explorviz.code.proto.FileMetricData.Builder getFileMetricBuilder(
        int index) {
      return getFileMetricFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public net.explorviz.code.proto.FileMetricDataOrBuilder getFileMetricOrBuilder(
        int index) {
      if (fileMetricBuilder_ == null) {
        return fileMetric_.get(index);  } else {
        return fileMetricBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public java.util.List<? extends net.explorviz.code.proto.FileMetricDataOrBuilder> 
         getFileMetricOrBuilderList() {
      if (fileMetricBuilder_ != null) {
        return fileMetricBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fileMetric_);
      }
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public net.explorviz.code.proto.FileMetricData.Builder addFileMetricBuilder() {
      return getFileMetricFieldBuilder().addBuilder(
          net.explorviz.code.proto.FileMetricData.getDefaultInstance());
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public net.explorviz.code.proto.FileMetricData.Builder addFileMetricBuilder(
        int index) {
      return getFileMetricFieldBuilder().addBuilder(
          index, net.explorviz.code.proto.FileMetricData.getDefaultInstance());
    }
    /**
     * <code>repeated .FileMetricData fileMetric = 8;</code>
     */
    public java.util.List<net.explorviz.code.proto.FileMetricData.Builder> 
         getFileMetricBuilderList() {
      return getFileMetricFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.explorviz.code.proto.FileMetricData, net.explorviz.code.proto.FileMetricData.Builder, net.explorviz.code.proto.FileMetricDataOrBuilder> 
        getFileMetricFieldBuilder() {
      if (fileMetricBuilder_ == null) {
        fileMetricBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.explorviz.code.proto.FileMetricData, net.explorviz.code.proto.FileMetricData.Builder, net.explorviz.code.proto.FileMetricDataOrBuilder>(
                fileMetric_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        fileMetric_ = null;
      }
      return fileMetricBuilder_;
    }

    private java.lang.Object commitTag_ = "";
    /**
     * <code>string commitTag = 9;</code>
     * @return The commitTag.
     */
    public java.lang.String getCommitTag() {
      java.lang.Object ref = commitTag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitTag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commitTag = 9;</code>
     * @return The bytes for commitTag.
     */
    public com.google.protobuf.ByteString
        getCommitTagBytes() {
      java.lang.Object ref = commitTag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commitTag = 9;</code>
     * @param value The commitTag to set.
     * @return This builder for chaining.
     */
    public Builder setCommitTag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commitTag_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string commitTag = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitTag() {
      commitTag_ = getDefaultInstance().getCommitTag();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string commitTag = 9;</code>
     * @param value The bytes for commitTag to set.
     * @return This builder for chaining.
     */
    public Builder setCommitTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commitTag_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object landscapeToken_ = "";
    /**
     * <code>string landscapeToken = 10;</code>
     * @return The landscapeToken.
     */
    public java.lang.String getLandscapeToken() {
      java.lang.Object ref = landscapeToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        landscapeToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string landscapeToken = 10;</code>
     * @return The bytes for landscapeToken.
     */
    public com.google.protobuf.ByteString
        getLandscapeTokenBytes() {
      java.lang.Object ref = landscapeToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        landscapeToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string landscapeToken = 10;</code>
     * @param value The landscapeToken to set.
     * @return This builder for chaining.
     */
    public Builder setLandscapeToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      landscapeToken_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string landscapeToken = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLandscapeToken() {
      landscapeToken_ = getDefaultInstance().getLandscapeToken();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string landscapeToken = 10;</code>
     * @param value The bytes for landscapeToken to set.
     * @return This builder for chaining.
     */
    public Builder setLandscapeTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      landscapeToken_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CommitReportData)
  }

  // @@protoc_insertion_point(class_scope:CommitReportData)
  private static final net.explorviz.code.proto.CommitReportData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.explorviz.code.proto.CommitReportData();
  }

  public static net.explorviz.code.proto.CommitReportData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommitReportData>
      PARSER = new com.google.protobuf.AbstractParser<CommitReportData>() {
    @java.lang.Override
    public CommitReportData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommitReportData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommitReportData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.explorviz.code.proto.CommitReportData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

