// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/commitReport.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

public interface CommitReportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommitReportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commitID = 1;</code>
   * @return The commitID.
   */
  java.lang.String getCommitID();
  /**
   * <code>string commitID = 1;</code>
   * @return The bytes for commitID.
   */
  com.google.protobuf.ByteString
      getCommitIDBytes();

  /**
   * <code>string parentCommitID = 2;</code>
   * @return The parentCommitID.
   */
  java.lang.String getParentCommitID();
  /**
   * <code>string parentCommitID = 2;</code>
   * @return The bytes for parentCommitID.
   */
  com.google.protobuf.ByteString
      getParentCommitIDBytes();

  /**
   * <code>string branchName = 3;</code>
   * @return The branchName.
   */
  java.lang.String getBranchName();
  /**
   * <code>string branchName = 3;</code>
   * @return The bytes for branchName.
   */
  com.google.protobuf.ByteString
      getBranchNameBytes();

  /**
   * <code>repeated string files = 4;</code>
   * @return A list containing the files.
   */
  java.util.List<java.lang.String>
      getFilesList();
  /**
   * <code>repeated string files = 4;</code>
   * @return The count of files.
   */
  int getFilesCount();
  /**
   * <code>repeated string files = 4;</code>
   * @param index The index of the element to return.
   * @return The files at the given index.
   */
  java.lang.String getFiles(int index);
  /**
   * <code>repeated string files = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the files at the given index.
   */
  com.google.protobuf.ByteString
      getFilesBytes(int index);

  /**
   * <code>repeated string modified = 5;</code>
   * @return A list containing the modified.
   */
  java.util.List<java.lang.String>
      getModifiedList();
  /**
   * <code>repeated string modified = 5;</code>
   * @return The count of modified.
   */
  int getModifiedCount();
  /**
   * <code>repeated string modified = 5;</code>
   * @param index The index of the element to return.
   * @return The modified at the given index.
   */
  java.lang.String getModified(int index);
  /**
   * <code>repeated string modified = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the modified at the given index.
   */
  com.google.protobuf.ByteString
      getModifiedBytes(int index);

  /**
   * <code>repeated string deleted = 6;</code>
   * @return A list containing the deleted.
   */
  java.util.List<java.lang.String>
      getDeletedList();
  /**
   * <code>repeated string deleted = 6;</code>
   * @return The count of deleted.
   */
  int getDeletedCount();
  /**
   * <code>repeated string deleted = 6;</code>
   * @param index The index of the element to return.
   * @return The deleted at the given index.
   */
  java.lang.String getDeleted(int index);
  /**
   * <code>repeated string deleted = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the deleted at the given index.
   */
  com.google.protobuf.ByteString
      getDeletedBytes(int index);

  /**
   * <code>repeated string added = 7;</code>
   * @return A list containing the added.
   */
  java.util.List<java.lang.String>
      getAddedList();
  /**
   * <code>repeated string added = 7;</code>
   * @return The count of added.
   */
  int getAddedCount();
  /**
   * <code>repeated string added = 7;</code>
   * @param index The index of the element to return.
   * @return The added at the given index.
   */
  java.lang.String getAdded(int index);
  /**
   * <code>repeated string added = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the added at the given index.
   */
  com.google.protobuf.ByteString
      getAddedBytes(int index);

  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  java.util.List<net.explorviz.code.proto.FileMetricData> 
      getFileMetricList();
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  net.explorviz.code.proto.FileMetricData getFileMetric(int index);
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  int getFileMetricCount();
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  java.util.List<? extends net.explorviz.code.proto.FileMetricDataOrBuilder> 
      getFileMetricOrBuilderList();
  /**
   * <code>repeated .FileMetricData fileMetric = 8;</code>
   */
  net.explorviz.code.proto.FileMetricDataOrBuilder getFileMetricOrBuilder(
      int index);

  /**
   * <code>string commitTag = 9;</code>
   * @return The commitTag.
   */
  java.lang.String getCommitTag();
  /**
   * <code>string commitTag = 9;</code>
   * @return The bytes for commitTag.
   */
  com.google.protobuf.ByteString
      getCommitTagBytes();

  /**
   * <code>string landscapeToken = 10;</code>
   * @return The landscapeToken.
   */
  java.lang.String getLandscapeToken();
  /**
   * <code>string landscapeToken = 10;</code>
   * @return The bytes for landscapeToken.
   */
  com.google.protobuf.ByteString
      getLandscapeTokenBytes();
}
