// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fileDataEvent.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

public interface FieldDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FieldData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated string modifier = 3;</code>
   * @return A list containing the modifier.
   */
  java.util.List<java.lang.String>
      getModifierList();
  /**
   * <code>repeated string modifier = 3;</code>
   * @return The count of modifier.
   */
  int getModifierCount();
  /**
   * <code>repeated string modifier = 3;</code>
   * @param index The index of the element to return.
   * @return The modifier at the given index.
   */
  java.lang.String getModifier(int index);
  /**
   * <code>repeated string modifier = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the modifier at the given index.
   */
  com.google.protobuf.ByteString
      getModifierBytes(int index);
}
