// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/commitReport.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

/**
 * Protobuf type {@code FileMetricData}
 */
public final class FileMetricData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileMetricData)
    FileMetricDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileMetricData.newBuilder() to construct.
  private FileMetricData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileMetricData() {
    fileName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileMetricData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.explorviz.code.proto.CommitReport.internal_static_FileMetricData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.explorviz.code.proto.CommitReport.internal_static_FileMetricData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.explorviz.code.proto.FileMetricData.class, net.explorviz.code.proto.FileMetricData.Builder.class);
  }

  public static final int FILENAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileName_ = "";
  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOC_FIELD_NUMBER = 2;
  private int loc_ = 0;
  /**
   * <code>int32 loc = 2;</code>
   * @return The loc.
   */
  @java.lang.Override
  public int getLoc() {
    return loc_;
  }

  public static final int CYCLOMATICCOMPLEXITY_FIELD_NUMBER = 3;
  private int cyclomaticComplexity_ = 0;
  /**
   * <code>int32 cyclomaticComplexity = 3;</code>
   * @return The cyclomaticComplexity.
   */
  @java.lang.Override
  public int getCyclomaticComplexity() {
    return cyclomaticComplexity_;
  }

  public static final int NUMBEROFMETHODS_FIELD_NUMBER = 4;
  private int numberOfMethods_ = 0;
  /**
   * <code>int32 numberOfMethods = 4;</code>
   * @return The numberOfMethods.
   */
  @java.lang.Override
  public int getNumberOfMethods() {
    return numberOfMethods_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
    }
    if (loc_ != 0) {
      output.writeInt32(2, loc_);
    }
    if (cyclomaticComplexity_ != 0) {
      output.writeInt32(3, cyclomaticComplexity_);
    }
    if (numberOfMethods_ != 0) {
      output.writeInt32(4, numberOfMethods_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
    }
    if (loc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, loc_);
    }
    if (cyclomaticComplexity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, cyclomaticComplexity_);
    }
    if (numberOfMethods_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, numberOfMethods_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.explorviz.code.proto.FileMetricData)) {
      return super.equals(obj);
    }
    net.explorviz.code.proto.FileMetricData other = (net.explorviz.code.proto.FileMetricData) obj;

    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (getLoc()
        != other.getLoc()) return false;
    if (getCyclomaticComplexity()
        != other.getCyclomaticComplexity()) return false;
    if (getNumberOfMethods()
        != other.getNumberOfMethods()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + LOC_FIELD_NUMBER;
    hash = (53 * hash) + getLoc();
    hash = (37 * hash) + CYCLOMATICCOMPLEXITY_FIELD_NUMBER;
    hash = (53 * hash) + getCyclomaticComplexity();
    hash = (37 * hash) + NUMBEROFMETHODS_FIELD_NUMBER;
    hash = (53 * hash) + getNumberOfMethods();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.explorviz.code.proto.FileMetricData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.explorviz.code.proto.FileMetricData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.explorviz.code.proto.FileMetricData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.FileMetricData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.explorviz.code.proto.FileMetricData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FileMetricData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileMetricData)
      net.explorviz.code.proto.FileMetricDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.explorviz.code.proto.CommitReport.internal_static_FileMetricData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.explorviz.code.proto.CommitReport.internal_static_FileMetricData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.explorviz.code.proto.FileMetricData.class, net.explorviz.code.proto.FileMetricData.Builder.class);
    }

    // Construct using net.explorviz.code.proto.FileMetricData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fileName_ = "";
      loc_ = 0;
      cyclomaticComplexity_ = 0;
      numberOfMethods_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.explorviz.code.proto.CommitReport.internal_static_FileMetricData_descriptor;
    }

    @java.lang.Override
    public net.explorviz.code.proto.FileMetricData getDefaultInstanceForType() {
      return net.explorviz.code.proto.FileMetricData.getDefaultInstance();
    }

    @java.lang.Override
    public net.explorviz.code.proto.FileMetricData build() {
      net.explorviz.code.proto.FileMetricData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.explorviz.code.proto.FileMetricData buildPartial() {
      net.explorviz.code.proto.FileMetricData result = new net.explorviz.code.proto.FileMetricData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.explorviz.code.proto.FileMetricData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fileName_ = fileName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.loc_ = loc_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cyclomaticComplexity_ = cyclomaticComplexity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.numberOfMethods_ = numberOfMethods_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.explorviz.code.proto.FileMetricData) {
        return mergeFrom((net.explorviz.code.proto.FileMetricData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.explorviz.code.proto.FileMetricData other) {
      if (other == net.explorviz.code.proto.FileMetricData.getDefaultInstance()) return this;
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getLoc() != 0) {
        setLoc(other.getLoc());
      }
      if (other.getCyclomaticComplexity() != 0) {
        setCyclomaticComplexity(other.getCyclomaticComplexity());
      }
      if (other.getNumberOfMethods() != 0) {
        setNumberOfMethods(other.getNumberOfMethods());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              loc_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              cyclomaticComplexity_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              numberOfMethods_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 1;</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 1;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 1;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int loc_ ;
    /**
     * <code>int32 loc = 2;</code>
     * @return The loc.
     */
    @java.lang.Override
    public int getLoc() {
      return loc_;
    }
    /**
     * <code>int32 loc = 2;</code>
     * @param value The loc to set.
     * @return This builder for chaining.
     */
    public Builder setLoc(int value) {

      loc_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 loc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLoc() {
      bitField0_ = (bitField0_ & ~0x00000002);
      loc_ = 0;
      onChanged();
      return this;
    }

    private int cyclomaticComplexity_ ;
    /**
     * <code>int32 cyclomaticComplexity = 3;</code>
     * @return The cyclomaticComplexity.
     */
    @java.lang.Override
    public int getCyclomaticComplexity() {
      return cyclomaticComplexity_;
    }
    /**
     * <code>int32 cyclomaticComplexity = 3;</code>
     * @param value The cyclomaticComplexity to set.
     * @return This builder for chaining.
     */
    public Builder setCyclomaticComplexity(int value) {

      cyclomaticComplexity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cyclomaticComplexity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCyclomaticComplexity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cyclomaticComplexity_ = 0;
      onChanged();
      return this;
    }

    private int numberOfMethods_ ;
    /**
     * <code>int32 numberOfMethods = 4;</code>
     * @return The numberOfMethods.
     */
    @java.lang.Override
    public int getNumberOfMethods() {
      return numberOfMethods_;
    }
    /**
     * <code>int32 numberOfMethods = 4;</code>
     * @param value The numberOfMethods to set.
     * @return This builder for chaining.
     */
    public Builder setNumberOfMethods(int value) {

      numberOfMethods_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberOfMethods = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberOfMethods() {
      bitField0_ = (bitField0_ & ~0x00000008);
      numberOfMethods_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileMetricData)
  }

  // @@protoc_insertion_point(class_scope:FileMetricData)
  private static final net.explorviz.code.proto.FileMetricData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.explorviz.code.proto.FileMetricData();
  }

  public static net.explorviz.code.proto.FileMetricData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileMetricData>
      PARSER = new com.google.protobuf.AbstractParser<FileMetricData>() {
    @java.lang.Override
    public FileMetricData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FileMetricData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileMetricData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.explorviz.code.proto.FileMetricData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

