// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fileDataEvent.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

public final class FileDataEvent {
  private FileDataEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MethodData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MethodData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MethodData_MetricEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MethodData_MetricEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ParameterData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ParameterData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FieldData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClassData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClassData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClassData_MethodDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClassData_MethodDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClassData_MetricEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClassData_MetricEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileData_ClassDataEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileData_ClassDataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileData_MetricEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileData_MetricEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/fileDataEvent.proto\032\033google/prot" +
      "obuf/empty.proto\"\365\001\n\nMethodData\022\022\n\nretur" +
      "nType\030\001 \001(\t\022\020\n\010modifier\030\002 \003(\t\022!\n\tparamet" +
      "er\030\003 \003(\0132\016.ParameterData\022\033\n\023outgoingMeth" +
      "odCalls\030\004 \003(\t\022\025\n\risConstructor\030\005 \001(\010\022\022\n\n" +
      "annotation\030\006 \003(\t\022\'\n\006metric\030\007 \003(\0132\027.Metho" +
      "dData.MetricEntry\032-\n\013MetricEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"=\n\rParameterDat" +
      "a\022\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\020\n\010modifie" +
      "r\030\003 \003(\t\"9\n\tFieldData\022\014\n\004name\030\001 \001(\t\022\014\n\004ty" +
      "pe\030\002 \001(\t\022\020\n\010modifier\030\003 \003(\t\"\262\003\n\tClassData" +
      "\022\030\n\004type\030\001 \001(\0162\n.ClassType\022\020\n\010modifier\030\002" +
      " \003(\t\022\021\n\tinterface\030\003 \003(\t\022\031\n\005field\030\004 \003(\0132\n" +
      ".FieldData\022\022\n\ninnerClass\030\005 \003(\t\022 \n\013constr" +
      "uctor\030\006 \003(\0132\013.MethodData\022.\n\nmethodData\030\007" +
      " \003(\0132\032.ClassData.MethodDataEntry\022\020\n\010vari" +
      "able\030\010 \003(\t\022\022\n\nsuperClass\030\t \001(\t\022\024\n\014enumCo" +
      "nstant\030\n \003(\t\022\022\n\nannotation\030\013 \003(\t\022&\n\006metr" +
      "ic\030\014 \003(\0132\026.ClassData.MetricEntry\032>\n\017Meth" +
      "odDataEntry\022\013\n\003key\030\001 \001(\t\022\032\n\005value\030\002 \001(\0132" +
      "\013.MethodData:\0028\001\032-\n\013MetricEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\351\002\n\010FileData\022\020\n\010" +
      "commitID\030\001 \001(\t\022\020\n\010fileName\030\002 \001(\t\022\023\n\013pack" +
      "ageName\030\003 \001(\t\022\022\n\nimportName\030\004 \003(\t\022+\n\tcla" +
      "ssData\030\005 \003(\0132\030.FileData.ClassDataEntry\022%" +
      "\n\006metric\030\006 \003(\0132\025.FileData.MetricEntry\022\016\n" +
      "\006author\030\007 \001(\t\022\025\n\rmodifiedLines\030\010 \001(\005\022\022\n\n" +
      "addedLines\030\t \001(\005\022\024\n\014deletedLines\030\n \001(\005\032<" +
      "\n\016ClassDataEntry\022\013\n\003key\030\001 \001(\t\022\031\n\005value\030\002" +
      " \001(\0132\n.ClassData:\0028\001\032-\n\013MetricEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*X\n\tClassType" +
      "\022\r\n\tINTERFACE\020\000\022\022\n\016ABSTRACT_CLASS\020\001\022\t\n\005C" +
      "LASS\020\002\022\010\n\004ENUM\020\003\022\023\n\017ANONYMOUS_CLASS\020\0042F\n" +
      "\017FileDataService\0223\n\014sendFileData\022\t.FileD" +
      "ata\032\026.google.protobuf.Empty\"\000B+\n\030net.exp" +
      "lorviz.code.protoB\rFileDataEventP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_MethodData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MethodData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MethodData_descriptor,
        new java.lang.String[] { "ReturnType", "Modifier", "Parameter", "OutgoingMethodCalls", "IsConstructor", "Annotation", "Metric", });
    internal_static_MethodData_MetricEntry_descriptor =
      internal_static_MethodData_descriptor.getNestedTypes().get(0);
    internal_static_MethodData_MetricEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MethodData_MetricEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ParameterData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ParameterData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ParameterData_descriptor,
        new java.lang.String[] { "Name", "Type", "Modifier", });
    internal_static_FieldData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FieldData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FieldData_descriptor,
        new java.lang.String[] { "Name", "Type", "Modifier", });
    internal_static_ClassData_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ClassData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClassData_descriptor,
        new java.lang.String[] { "Type", "Modifier", "Interface", "Field", "InnerClass", "Constructor", "MethodData", "Variable", "SuperClass", "EnumConstant", "Annotation", "Metric", });
    internal_static_ClassData_MethodDataEntry_descriptor =
      internal_static_ClassData_descriptor.getNestedTypes().get(0);
    internal_static_ClassData_MethodDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClassData_MethodDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ClassData_MetricEntry_descriptor =
      internal_static_ClassData_descriptor.getNestedTypes().get(1);
    internal_static_ClassData_MetricEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClassData_MetricEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_FileData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_FileData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileData_descriptor,
        new java.lang.String[] { "CommitID", "FileName", "PackageName", "ImportName", "ClassData", "Metric", "Author", "ModifiedLines", "AddedLines", "DeletedLines", });
    internal_static_FileData_ClassDataEntry_descriptor =
      internal_static_FileData_descriptor.getNestedTypes().get(0);
    internal_static_FileData_ClassDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileData_ClassDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_FileData_MetricEntry_descriptor =
      internal_static_FileData_descriptor.getNestedTypes().get(1);
    internal_static_FileData_MetricEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileData_MetricEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
