// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/commitReport.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

public interface FileMetricDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileMetricData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>int32 loc = 2;</code>
   * @return The loc.
   */
  int getLoc();

  /**
   * <code>int32 cyclomaticComplexity = 3;</code>
   * @return The cyclomaticComplexity.
   */
  int getCyclomaticComplexity();

  /**
   * <code>int32 numberOfMethods = 4;</code>
   * @return The numberOfMethods.
   */
  int getNumberOfMethods();
}
