// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fileDataEvent.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

/**
 * Protobuf type {@code FileData}
 */
public final class FileData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileData)
    FileDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileData.newBuilder() to construct.
  private FileData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileData() {
    commitID_ = "";
    fileName_ = "";
    packageName_ = "";
    importName_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    author_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.explorviz.code.proto.FileDataEvent.internal_static_FileData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 5:
        return internalGetClassData();
      case 6:
        return internalGetMetric();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.explorviz.code.proto.FileDataEvent.internal_static_FileData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.explorviz.code.proto.FileData.class, net.explorviz.code.proto.FileData.Builder.class);
  }

  public static final int COMMITID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object commitID_ = "";
  /**
   * <code>string commitID = 1;</code>
   * @return The commitID.
   */
  @java.lang.Override
  public java.lang.String getCommitID() {
    java.lang.Object ref = commitID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      commitID_ = s;
      return s;
    }
  }
  /**
   * <code>string commitID = 1;</code>
   * @return The bytes for commitID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommitIDBytes() {
    java.lang.Object ref = commitID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      commitID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILENAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fileName_ = "";
  /**
   * <code>string fileName = 2;</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string fileName = 2;</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGENAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object packageName_ = "";
  /**
   * <code>string packageName = 3;</code>
   * @return The packageName.
   */
  @java.lang.Override
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }
  /**
   * <code>string packageName = 3;</code>
   * @return The bytes for packageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMPORTNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList importName_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string importName = 4;</code>
   * @return A list containing the importName.
   */
  public com.google.protobuf.ProtocolStringList
      getImportNameList() {
    return importName_;
  }
  /**
   * <code>repeated string importName = 4;</code>
   * @return The count of importName.
   */
  public int getImportNameCount() {
    return importName_.size();
  }
  /**
   * <code>repeated string importName = 4;</code>
   * @param index The index of the element to return.
   * @return The importName at the given index.
   */
  public java.lang.String getImportName(int index) {
    return importName_.get(index);
  }
  /**
   * <code>repeated string importName = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the importName at the given index.
   */
  public com.google.protobuf.ByteString
      getImportNameBytes(int index) {
    return importName_.getByteString(index);
  }

  public static final int CLASSDATA_FIELD_NUMBER = 5;
  private static final class ClassDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, net.explorviz.code.proto.ClassData> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, net.explorviz.code.proto.ClassData>newDefaultInstance(
                net.explorviz.code.proto.FileDataEvent.internal_static_FileData_ClassDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                net.explorviz.code.proto.ClassData.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, net.explorviz.code.proto.ClassData> classData_;
  private com.google.protobuf.MapField<java.lang.String, net.explorviz.code.proto.ClassData>
  internalGetClassData() {
    if (classData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ClassDataDefaultEntryHolder.defaultEntry);
    }
    return classData_;
  }
  public int getClassDataCount() {
    return internalGetClassData().getMap().size();
  }
  /**
   * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
   */
  @java.lang.Override
  public boolean containsClassData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetClassData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getClassDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> getClassData() {
    return getClassDataMap();
  }
  /**
   * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> getClassDataMap() {
    return internalGetClassData().getMap();
  }
  /**
   * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
   */
  @java.lang.Override
  public /* nullable */
net.explorviz.code.proto.ClassData getClassDataOrDefault(
      java.lang.String key,
      /* nullable */
net.explorviz.code.proto.ClassData defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> map =
        internalGetClassData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
   */
  @java.lang.Override
  public net.explorviz.code.proto.ClassData getClassDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> map =
        internalGetClassData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int METRIC_FIELD_NUMBER = 6;
  private static final class MetricDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                net.explorviz.code.proto.FileDataEvent.internal_static_FileData_MetricEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metric_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetric() {
    if (metric_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetricDefaultEntryHolder.defaultEntry);
    }
    return metric_;
  }
  public int getMetricCount() {
    return internalGetMetric().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; metric = 6;</code>
   */
  @java.lang.Override
  public boolean containsMetric(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetric().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetricMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetric() {
    return getMetricMap();
  }
  /**
   * <code>map&lt;string, string&gt; metric = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetricMap() {
    return internalGetMetric().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; metric = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetricOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetric().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; metric = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getMetricOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetric().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int AUTHOR_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object author_ = "";
  /**
   * <code>string author = 7;</code>
   * @return The author.
   */
  @java.lang.Override
  public java.lang.String getAuthor() {
    java.lang.Object ref = author_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      author_ = s;
      return s;
    }
  }
  /**
   * <code>string author = 7;</code>
   * @return The bytes for author.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorBytes() {
    java.lang.Object ref = author_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      author_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODIFIEDLINES_FIELD_NUMBER = 8;
  private int modifiedLines_ = 0;
  /**
   * <code>int32 modifiedLines = 8;</code>
   * @return The modifiedLines.
   */
  @java.lang.Override
  public int getModifiedLines() {
    return modifiedLines_;
  }

  public static final int ADDEDLINES_FIELD_NUMBER = 9;
  private int addedLines_ = 0;
  /**
   * <code>int32 addedLines = 9;</code>
   * @return The addedLines.
   */
  @java.lang.Override
  public int getAddedLines() {
    return addedLines_;
  }

  public static final int DELETEDLINES_FIELD_NUMBER = 10;
  private int deletedLines_ = 0;
  /**
   * <code>int32 deletedLines = 10;</code>
   * @return The deletedLines.
   */
  @java.lang.Override
  public int getDeletedLines() {
    return deletedLines_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commitID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(packageName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, packageName_);
    }
    for (int i = 0; i < importName_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, importName_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetClassData(),
        ClassDataDefaultEntryHolder.defaultEntry,
        5);
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetric(),
        MetricDefaultEntryHolder.defaultEntry,
        6);
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(author_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, author_);
    }
    if (modifiedLines_ != 0) {
      output.writeInt32(8, modifiedLines_);
    }
    if (addedLines_ != 0) {
      output.writeInt32(9, addedLines_);
    }
    if (deletedLines_ != 0) {
      output.writeInt32(10, deletedLines_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(commitID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commitID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(packageName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, packageName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < importName_.size(); i++) {
        dataSize += computeStringSizeNoTag(importName_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getImportNameList().size();
    }
    for (java.util.Map.Entry<java.lang.String, net.explorviz.code.proto.ClassData> entry
         : internalGetClassData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, net.explorviz.code.proto.ClassData>
      classData__ = ClassDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, classData__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetric().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metric__ = MetricDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, metric__);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(author_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, author_);
    }
    if (modifiedLines_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, modifiedLines_);
    }
    if (addedLines_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, addedLines_);
    }
    if (deletedLines_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, deletedLines_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.explorviz.code.proto.FileData)) {
      return super.equals(obj);
    }
    net.explorviz.code.proto.FileData other = (net.explorviz.code.proto.FileData) obj;

    if (!getCommitID()
        .equals(other.getCommitID())) return false;
    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (!getPackageName()
        .equals(other.getPackageName())) return false;
    if (!getImportNameList()
        .equals(other.getImportNameList())) return false;
    if (!internalGetClassData().equals(
        other.internalGetClassData())) return false;
    if (!internalGetMetric().equals(
        other.internalGetMetric())) return false;
    if (!getAuthor()
        .equals(other.getAuthor())) return false;
    if (getModifiedLines()
        != other.getModifiedLines()) return false;
    if (getAddedLines()
        != other.getAddedLines()) return false;
    if (getDeletedLines()
        != other.getDeletedLines()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMITID_FIELD_NUMBER;
    hash = (53 * hash) + getCommitID().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    if (getImportNameCount() > 0) {
      hash = (37 * hash) + IMPORTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getImportNameList().hashCode();
    }
    if (!internalGetClassData().getMap().isEmpty()) {
      hash = (37 * hash) + CLASSDATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetClassData().hashCode();
    }
    if (!internalGetMetric().getMap().isEmpty()) {
      hash = (37 * hash) + METRIC_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetric().hashCode();
    }
    hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
    hash = (53 * hash) + getAuthor().hashCode();
    hash = (37 * hash) + MODIFIEDLINES_FIELD_NUMBER;
    hash = (53 * hash) + getModifiedLines();
    hash = (37 * hash) + ADDEDLINES_FIELD_NUMBER;
    hash = (53 * hash) + getAddedLines();
    hash = (37 * hash) + DELETEDLINES_FIELD_NUMBER;
    hash = (53 * hash) + getDeletedLines();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.explorviz.code.proto.FileData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.explorviz.code.proto.FileData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.explorviz.code.proto.FileData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.FileData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.explorviz.code.proto.FileData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FileData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileData)
      net.explorviz.code.proto.FileDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.explorviz.code.proto.FileDataEvent.internal_static_FileData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetClassData();
        case 6:
          return internalGetMetric();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableClassData();
        case 6:
          return internalGetMutableMetric();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.explorviz.code.proto.FileDataEvent.internal_static_FileData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.explorviz.code.proto.FileData.class, net.explorviz.code.proto.FileData.Builder.class);
    }

    // Construct using net.explorviz.code.proto.FileData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      commitID_ = "";
      fileName_ = "";
      packageName_ = "";
      importName_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableClassData().clear();
      internalGetMutableMetric().clear();
      author_ = "";
      modifiedLines_ = 0;
      addedLines_ = 0;
      deletedLines_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.explorviz.code.proto.FileDataEvent.internal_static_FileData_descriptor;
    }

    @java.lang.Override
    public net.explorviz.code.proto.FileData getDefaultInstanceForType() {
      return net.explorviz.code.proto.FileData.getDefaultInstance();
    }

    @java.lang.Override
    public net.explorviz.code.proto.FileData build() {
      net.explorviz.code.proto.FileData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.explorviz.code.proto.FileData buildPartial() {
      net.explorviz.code.proto.FileData result = new net.explorviz.code.proto.FileData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.explorviz.code.proto.FileData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.commitID_ = commitID_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.fileName_ = fileName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.packageName_ = packageName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        importName_.makeImmutable();
        result.importName_ = importName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.classData_ = internalGetClassData().build(ClassDataDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.metric_ = internalGetMetric();
        result.metric_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.author_ = author_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.modifiedLines_ = modifiedLines_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.addedLines_ = addedLines_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.deletedLines_ = deletedLines_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.explorviz.code.proto.FileData) {
        return mergeFrom((net.explorviz.code.proto.FileData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.explorviz.code.proto.FileData other) {
      if (other == net.explorviz.code.proto.FileData.getDefaultInstance()) return this;
      if (!other.getCommitID().isEmpty()) {
        commitID_ = other.commitID_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.importName_.isEmpty()) {
        if (importName_.isEmpty()) {
          importName_ = other.importName_;
          bitField0_ |= 0x00000008;
        } else {
          ensureImportNameIsMutable();
          importName_.addAll(other.importName_);
        }
        onChanged();
      }
      internalGetMutableClassData().mergeFrom(
          other.internalGetClassData());
      bitField0_ |= 0x00000010;
      internalGetMutableMetric().mergeFrom(
          other.internalGetMetric());
      bitField0_ |= 0x00000020;
      if (!other.getAuthor().isEmpty()) {
        author_ = other.author_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getModifiedLines() != 0) {
        setModifiedLines(other.getModifiedLines());
      }
      if (other.getAddedLines() != 0) {
        setAddedLines(other.getAddedLines());
      }
      if (other.getDeletedLines() != 0) {
        setDeletedLines(other.getDeletedLines());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              commitID_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              fileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              packageName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureImportNameIsMutable();
              importName_.add(s);
              break;
            } // case 34
            case 42: {
              com.google.protobuf.MapEntry<java.lang.String, net.explorviz.code.proto.ClassData>
              classData__ = input.readMessage(
                  ClassDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableClassData().ensureBuilderMap().put(
                  classData__.getKey(), classData__.getValue());
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metric__ = input.readMessage(
                  MetricDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetric().getMutableMap().put(
                  metric__.getKey(), metric__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              author_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              modifiedLines_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              addedLines_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              deletedLines_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object commitID_ = "";
    /**
     * <code>string commitID = 1;</code>
     * @return The commitID.
     */
    public java.lang.String getCommitID() {
      java.lang.Object ref = commitID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        commitID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string commitID = 1;</code>
     * @return The bytes for commitID.
     */
    public com.google.protobuf.ByteString
        getCommitIDBytes() {
      java.lang.Object ref = commitID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commitID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string commitID = 1;</code>
     * @param value The commitID to set.
     * @return This builder for chaining.
     */
    public Builder setCommitID(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      commitID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string commitID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommitID() {
      commitID_ = getDefaultInstance().getCommitID();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string commitID = 1;</code>
     * @param value The bytes for commitID to set.
     * @return This builder for chaining.
     */
    public Builder setCommitIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      commitID_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string fileName = 2;</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fileName = 2;</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fileName = 2;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string fileName = 2;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <code>string packageName = 3;</code>
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string packageName = 3;</code>
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string packageName = 3;</code>
     * @param value The packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      packageName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string packageName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageName() {
      packageName_ = getDefaultInstance().getPackageName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string packageName = 3;</code>
     * @param value The bytes for packageName to set.
     * @return This builder for chaining.
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      packageName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList importName_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureImportNameIsMutable() {
      if (!importName_.isModifiable()) {
        importName_ = new com.google.protobuf.LazyStringArrayList(importName_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @return A list containing the importName.
     */
    public com.google.protobuf.ProtocolStringList
        getImportNameList() {
      importName_.makeImmutable();
      return importName_;
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @return The count of importName.
     */
    public int getImportNameCount() {
      return importName_.size();
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @param index The index of the element to return.
     * @return The importName at the given index.
     */
    public java.lang.String getImportName(int index) {
      return importName_.get(index);
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the importName at the given index.
     */
    public com.google.protobuf.ByteString
        getImportNameBytes(int index) {
      return importName_.getByteString(index);
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @param index The index to set the value at.
     * @param value The importName to set.
     * @return This builder for chaining.
     */
    public Builder setImportName(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureImportNameIsMutable();
      importName_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @param value The importName to add.
     * @return This builder for chaining.
     */
    public Builder addImportName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureImportNameIsMutable();
      importName_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @param values The importName to add.
     * @return This builder for chaining.
     */
    public Builder addAllImportName(
        java.lang.Iterable<java.lang.String> values) {
      ensureImportNameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, importName_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImportName() {
      importName_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string importName = 4;</code>
     * @param value The bytes of the importName to add.
     * @return This builder for chaining.
     */
    public Builder addImportNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureImportNameIsMutable();
      importName_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private static final class ClassDataConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder, net.explorviz.code.proto.ClassData> {
      @java.lang.Override
      public net.explorviz.code.proto.ClassData build(net.explorviz.code.proto.ClassDataOrBuilder val) {
        if (val instanceof net.explorviz.code.proto.ClassData) { return (net.explorviz.code.proto.ClassData) val; }
        return ((net.explorviz.code.proto.ClassData.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, net.explorviz.code.proto.ClassData> defaultEntry() {
        return ClassDataDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ClassDataConverter classDataConverter = new ClassDataConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder, net.explorviz.code.proto.ClassData, net.explorviz.code.proto.ClassData.Builder> classData_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder, net.explorviz.code.proto.ClassData, net.explorviz.code.proto.ClassData.Builder>
        internalGetClassData() {
      if (classData_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(classDataConverter);
      }
      return classData_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder, net.explorviz.code.proto.ClassData, net.explorviz.code.proto.ClassData.Builder>
        internalGetMutableClassData() {
      if (classData_ == null) {
        classData_ = new com.google.protobuf.MapFieldBuilder<>(classDataConverter);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return classData_;
    }
    public int getClassDataCount() {
      return internalGetClassData().ensureBuilderMap().size();
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    @java.lang.Override
    public boolean containsClassData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetClassData().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getClassDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> getClassData() {
      return getClassDataMap();
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> getClassDataMap() {
      return internalGetClassData().getImmutableMap();
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    @java.lang.Override
    public /* nullable */
net.explorviz.code.proto.ClassData getClassDataOrDefault(
        java.lang.String key,
        /* nullable */
net.explorviz.code.proto.ClassData defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder> map = internalGetMutableClassData().ensureBuilderMap();
      return map.containsKey(key) ? classDataConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    @java.lang.Override
    public net.explorviz.code.proto.ClassData getClassDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder> map = internalGetMutableClassData().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return classDataConverter.build(map.get(key));
    }
    public Builder clearClassData() {
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableClassData().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    public Builder removeClassData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableClassData().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData>
        getMutableClassData() {
      bitField0_ |= 0x00000010;
      return internalGetMutableClassData().ensureMessageMap();
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    public Builder putClassData(
        java.lang.String key,
        net.explorviz.code.proto.ClassData value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableClassData().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    public Builder putAllClassData(
        java.util.Map<java.lang.String, net.explorviz.code.proto.ClassData> values) {
      for (java.util.Map.Entry<java.lang.String, net.explorviz.code.proto.ClassData> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableClassData().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>map&lt;string, .ClassData&gt; classData = 5;</code>
     */
    public net.explorviz.code.proto.ClassData.Builder putClassDataBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, net.explorviz.code.proto.ClassDataOrBuilder> builderMap = internalGetMutableClassData().ensureBuilderMap();
      net.explorviz.code.proto.ClassDataOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = net.explorviz.code.proto.ClassData.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof net.explorviz.code.proto.ClassData) {
        entry = ((net.explorviz.code.proto.ClassData) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (net.explorviz.code.proto.ClassData.Builder) entry;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metric_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetric() {
      if (metric_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetricDefaultEntryHolder.defaultEntry);
      }
      return metric_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetric() {
      if (metric_ == null) {
        metric_ = com.google.protobuf.MapField.newMapField(
            MetricDefaultEntryHolder.defaultEntry);
      }
      if (!metric_.isMutable()) {
        metric_ = metric_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return metric_;
    }
    public int getMetricCount() {
      return internalGetMetric().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    @java.lang.Override
    public boolean containsMetric(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetric().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetricMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetric() {
      return getMetricMap();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetricMap() {
      return internalGetMetric().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetricOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetric().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getMetricOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetric().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetric() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableMetric().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    public Builder removeMetric(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetric().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetric() {
      bitField0_ |= 0x00000020;
      return internalGetMutableMetric().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    public Builder putMetric(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetric().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metric = 6;</code>
     */
    public Builder putAllMetric(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetric().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }

    private java.lang.Object author_ = "";
    /**
     * <code>string author = 7;</code>
     * @return The author.
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string author = 7;</code>
     * @return The bytes for author.
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string author = 7;</code>
     * @param value The author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      author_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string author = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthor() {
      author_ = getDefaultInstance().getAuthor();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string author = 7;</code>
     * @param value The bytes for author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      author_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private int modifiedLines_ ;
    /**
     * <code>int32 modifiedLines = 8;</code>
     * @return The modifiedLines.
     */
    @java.lang.Override
    public int getModifiedLines() {
      return modifiedLines_;
    }
    /**
     * <code>int32 modifiedLines = 8;</code>
     * @param value The modifiedLines to set.
     * @return This builder for chaining.
     */
    public Builder setModifiedLines(int value) {

      modifiedLines_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 modifiedLines = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifiedLines() {
      bitField0_ = (bitField0_ & ~0x00000080);
      modifiedLines_ = 0;
      onChanged();
      return this;
    }

    private int addedLines_ ;
    /**
     * <code>int32 addedLines = 9;</code>
     * @return The addedLines.
     */
    @java.lang.Override
    public int getAddedLines() {
      return addedLines_;
    }
    /**
     * <code>int32 addedLines = 9;</code>
     * @param value The addedLines to set.
     * @return This builder for chaining.
     */
    public Builder setAddedLines(int value) {

      addedLines_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 addedLines = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddedLines() {
      bitField0_ = (bitField0_ & ~0x00000100);
      addedLines_ = 0;
      onChanged();
      return this;
    }

    private int deletedLines_ ;
    /**
     * <code>int32 deletedLines = 10;</code>
     * @return The deletedLines.
     */
    @java.lang.Override
    public int getDeletedLines() {
      return deletedLines_;
    }
    /**
     * <code>int32 deletedLines = 10;</code>
     * @param value The deletedLines to set.
     * @return This builder for chaining.
     */
    public Builder setDeletedLines(int value) {

      deletedLines_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 deletedLines = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletedLines() {
      bitField0_ = (bitField0_ & ~0x00000200);
      deletedLines_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileData)
  }

  // @@protoc_insertion_point(class_scope:FileData)
  private static final net.explorviz.code.proto.FileData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.explorviz.code.proto.FileData();
  }

  public static net.explorviz.code.proto.FileData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileData>
      PARSER = new com.google.protobuf.AbstractParser<FileData>() {
    @java.lang.Override
    public FileData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FileData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.explorviz.code.proto.FileData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

