// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fileDataEvent.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

public interface MethodDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MethodData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string returnType = 1;</code>
   * @return The returnType.
   */
  java.lang.String getReturnType();
  /**
   * <code>string returnType = 1;</code>
   * @return The bytes for returnType.
   */
  com.google.protobuf.ByteString
      getReturnTypeBytes();

  /**
   * <code>repeated string modifier = 2;</code>
   * @return A list containing the modifier.
   */
  java.util.List<java.lang.String>
      getModifierList();
  /**
   * <code>repeated string modifier = 2;</code>
   * @return The count of modifier.
   */
  int getModifierCount();
  /**
   * <code>repeated string modifier = 2;</code>
   * @param index The index of the element to return.
   * @return The modifier at the given index.
   */
  java.lang.String getModifier(int index);
  /**
   * <code>repeated string modifier = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the modifier at the given index.
   */
  com.google.protobuf.ByteString
      getModifierBytes(int index);

  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  java.util.List<net.explorviz.code.proto.ParameterData> 
      getParameterList();
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  net.explorviz.code.proto.ParameterData getParameter(int index);
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  int getParameterCount();
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  java.util.List<? extends net.explorviz.code.proto.ParameterDataOrBuilder> 
      getParameterOrBuilderList();
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  net.explorviz.code.proto.ParameterDataOrBuilder getParameterOrBuilder(
      int index);

  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @return A list containing the outgoingMethodCalls.
   */
  java.util.List<java.lang.String>
      getOutgoingMethodCallsList();
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @return The count of outgoingMethodCalls.
   */
  int getOutgoingMethodCallsCount();
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @param index The index of the element to return.
   * @return The outgoingMethodCalls at the given index.
   */
  java.lang.String getOutgoingMethodCalls(int index);
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outgoingMethodCalls at the given index.
   */
  com.google.protobuf.ByteString
      getOutgoingMethodCallsBytes(int index);

  /**
   * <code>bool isConstructor = 5;</code>
   * @return The isConstructor.
   */
  boolean getIsConstructor();

  /**
   * <code>repeated string annotation = 6;</code>
   * @return A list containing the annotation.
   */
  java.util.List<java.lang.String>
      getAnnotationList();
  /**
   * <code>repeated string annotation = 6;</code>
   * @return The count of annotation.
   */
  int getAnnotationCount();
  /**
   * <code>repeated string annotation = 6;</code>
   * @param index The index of the element to return.
   * @return The annotation at the given index.
   */
  java.lang.String getAnnotation(int index);
  /**
   * <code>repeated string annotation = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the annotation at the given index.
   */
  com.google.protobuf.ByteString
      getAnnotationBytes(int index);

  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  int getMetricCount();
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  boolean containsMetric(
      java.lang.String key);
  /**
   * Use {@link #getMetricMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetric();
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetricMap();
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  /* nullable */
java.lang.String getMetricOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  java.lang.String getMetricOrThrow(
      java.lang.String key);
}
