// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fileDataEvent.proto

// Protobuf Java Version: 3.25.1
package net.explorviz.code.proto;

/**
 * Protobuf type {@code MethodData}
 */
public final class MethodData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MethodData)
    MethodDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MethodData.newBuilder() to construct.
  private MethodData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MethodData() {
    returnType_ = "";
    modifier_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    parameter_ = java.util.Collections.emptyList();
    outgoingMethodCalls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    annotation_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MethodData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.explorviz.code.proto.FileDataEvent.internal_static_MethodData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 7:
        return internalGetMetric();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.explorviz.code.proto.FileDataEvent.internal_static_MethodData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.explorviz.code.proto.MethodData.class, net.explorviz.code.proto.MethodData.Builder.class);
  }

  public static final int RETURNTYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object returnType_ = "";
  /**
   * <code>string returnType = 1;</code>
   * @return The returnType.
   */
  @java.lang.Override
  public java.lang.String getReturnType() {
    java.lang.Object ref = returnType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      returnType_ = s;
      return s;
    }
  }
  /**
   * <code>string returnType = 1;</code>
   * @return The bytes for returnType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReturnTypeBytes() {
    java.lang.Object ref = returnType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      returnType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODIFIER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList modifier_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string modifier = 2;</code>
   * @return A list containing the modifier.
   */
  public com.google.protobuf.ProtocolStringList
      getModifierList() {
    return modifier_;
  }
  /**
   * <code>repeated string modifier = 2;</code>
   * @return The count of modifier.
   */
  public int getModifierCount() {
    return modifier_.size();
  }
  /**
   * <code>repeated string modifier = 2;</code>
   * @param index The index of the element to return.
   * @return The modifier at the given index.
   */
  public java.lang.String getModifier(int index) {
    return modifier_.get(index);
  }
  /**
   * <code>repeated string modifier = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the modifier at the given index.
   */
  public com.google.protobuf.ByteString
      getModifierBytes(int index) {
    return modifier_.getByteString(index);
  }

  public static final int PARAMETER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<net.explorviz.code.proto.ParameterData> parameter_;
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  @java.lang.Override
  public java.util.List<net.explorviz.code.proto.ParameterData> getParameterList() {
    return parameter_;
  }
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends net.explorviz.code.proto.ParameterDataOrBuilder> 
      getParameterOrBuilderList() {
    return parameter_;
  }
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  @java.lang.Override
  public int getParameterCount() {
    return parameter_.size();
  }
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  @java.lang.Override
  public net.explorviz.code.proto.ParameterData getParameter(int index) {
    return parameter_.get(index);
  }
  /**
   * <code>repeated .ParameterData parameter = 3;</code>
   */
  @java.lang.Override
  public net.explorviz.code.proto.ParameterDataOrBuilder getParameterOrBuilder(
      int index) {
    return parameter_.get(index);
  }

  public static final int OUTGOINGMETHODCALLS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList outgoingMethodCalls_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @return A list containing the outgoingMethodCalls.
   */
  public com.google.protobuf.ProtocolStringList
      getOutgoingMethodCallsList() {
    return outgoingMethodCalls_;
  }
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @return The count of outgoingMethodCalls.
   */
  public int getOutgoingMethodCallsCount() {
    return outgoingMethodCalls_.size();
  }
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @param index The index of the element to return.
   * @return The outgoingMethodCalls at the given index.
   */
  public java.lang.String getOutgoingMethodCalls(int index) {
    return outgoingMethodCalls_.get(index);
  }
  /**
   * <code>repeated string outgoingMethodCalls = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the outgoingMethodCalls at the given index.
   */
  public com.google.protobuf.ByteString
      getOutgoingMethodCallsBytes(int index) {
    return outgoingMethodCalls_.getByteString(index);
  }

  public static final int ISCONSTRUCTOR_FIELD_NUMBER = 5;
  private boolean isConstructor_ = false;
  /**
   * <code>bool isConstructor = 5;</code>
   * @return The isConstructor.
   */
  @java.lang.Override
  public boolean getIsConstructor() {
    return isConstructor_;
  }

  public static final int ANNOTATION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList annotation_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string annotation = 6;</code>
   * @return A list containing the annotation.
   */
  public com.google.protobuf.ProtocolStringList
      getAnnotationList() {
    return annotation_;
  }
  /**
   * <code>repeated string annotation = 6;</code>
   * @return The count of annotation.
   */
  public int getAnnotationCount() {
    return annotation_.size();
  }
  /**
   * <code>repeated string annotation = 6;</code>
   * @param index The index of the element to return.
   * @return The annotation at the given index.
   */
  public java.lang.String getAnnotation(int index) {
    return annotation_.get(index);
  }
  /**
   * <code>repeated string annotation = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the annotation at the given index.
   */
  public com.google.protobuf.ByteString
      getAnnotationBytes(int index) {
    return annotation_.getByteString(index);
  }

  public static final int METRIC_FIELD_NUMBER = 7;
  private static final class MetricDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                net.explorviz.code.proto.FileDataEvent.internal_static_MethodData_MetricEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metric_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetric() {
    if (metric_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetricDefaultEntryHolder.defaultEntry);
    }
    return metric_;
  }
  public int getMetricCount() {
    return internalGetMetric().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  @java.lang.Override
  public boolean containsMetric(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetric().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetricMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetric() {
    return getMetricMap();
  }
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetricMap() {
    return internalGetMetric().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetricOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetric().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; metric = 7;</code>
   */
  @java.lang.Override
  public java.lang.String getMetricOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetric().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, returnType_);
    }
    for (int i = 0; i < modifier_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, modifier_.getRaw(i));
    }
    for (int i = 0; i < parameter_.size(); i++) {
      output.writeMessage(3, parameter_.get(i));
    }
    for (int i = 0; i < outgoingMethodCalls_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, outgoingMethodCalls_.getRaw(i));
    }
    if (isConstructor_ != false) {
      output.writeBool(5, isConstructor_);
    }
    for (int i = 0; i < annotation_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, annotation_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetric(),
        MetricDefaultEntryHolder.defaultEntry,
        7);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(returnType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, returnType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < modifier_.size(); i++) {
        dataSize += computeStringSizeNoTag(modifier_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getModifierList().size();
    }
    for (int i = 0; i < parameter_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, parameter_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < outgoingMethodCalls_.size(); i++) {
        dataSize += computeStringSizeNoTag(outgoingMethodCalls_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOutgoingMethodCallsList().size();
    }
    if (isConstructor_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isConstructor_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < annotation_.size(); i++) {
        dataSize += computeStringSizeNoTag(annotation_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAnnotationList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetric().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metric__ = MetricDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, metric__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.explorviz.code.proto.MethodData)) {
      return super.equals(obj);
    }
    net.explorviz.code.proto.MethodData other = (net.explorviz.code.proto.MethodData) obj;

    if (!getReturnType()
        .equals(other.getReturnType())) return false;
    if (!getModifierList()
        .equals(other.getModifierList())) return false;
    if (!getParameterList()
        .equals(other.getParameterList())) return false;
    if (!getOutgoingMethodCallsList()
        .equals(other.getOutgoingMethodCallsList())) return false;
    if (getIsConstructor()
        != other.getIsConstructor()) return false;
    if (!getAnnotationList()
        .equals(other.getAnnotationList())) return false;
    if (!internalGetMetric().equals(
        other.internalGetMetric())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RETURNTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getReturnType().hashCode();
    if (getModifierCount() > 0) {
      hash = (37 * hash) + MODIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getModifierList().hashCode();
    }
    if (getParameterCount() > 0) {
      hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getParameterList().hashCode();
    }
    if (getOutgoingMethodCallsCount() > 0) {
      hash = (37 * hash) + OUTGOINGMETHODCALLS_FIELD_NUMBER;
      hash = (53 * hash) + getOutgoingMethodCallsList().hashCode();
    }
    hash = (37 * hash) + ISCONSTRUCTOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsConstructor());
    if (getAnnotationCount() > 0) {
      hash = (37 * hash) + ANNOTATION_FIELD_NUMBER;
      hash = (53 * hash) + getAnnotationList().hashCode();
    }
    if (!internalGetMetric().getMap().isEmpty()) {
      hash = (37 * hash) + METRIC_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetric().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.explorviz.code.proto.MethodData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.explorviz.code.proto.MethodData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.explorviz.code.proto.MethodData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.explorviz.code.proto.MethodData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.explorviz.code.proto.MethodData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MethodData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MethodData)
      net.explorviz.code.proto.MethodDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.explorviz.code.proto.FileDataEvent.internal_static_MethodData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMetric();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 7:
          return internalGetMutableMetric();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.explorviz.code.proto.FileDataEvent.internal_static_MethodData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.explorviz.code.proto.MethodData.class, net.explorviz.code.proto.MethodData.Builder.class);
    }

    // Construct using net.explorviz.code.proto.MethodData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      returnType_ = "";
      modifier_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (parameterBuilder_ == null) {
        parameter_ = java.util.Collections.emptyList();
      } else {
        parameter_ = null;
        parameterBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      outgoingMethodCalls_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      isConstructor_ = false;
      annotation_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableMetric().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.explorviz.code.proto.FileDataEvent.internal_static_MethodData_descriptor;
    }

    @java.lang.Override
    public net.explorviz.code.proto.MethodData getDefaultInstanceForType() {
      return net.explorviz.code.proto.MethodData.getDefaultInstance();
    }

    @java.lang.Override
    public net.explorviz.code.proto.MethodData build() {
      net.explorviz.code.proto.MethodData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.explorviz.code.proto.MethodData buildPartial() {
      net.explorviz.code.proto.MethodData result = new net.explorviz.code.proto.MethodData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(net.explorviz.code.proto.MethodData result) {
      if (parameterBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          parameter_ = java.util.Collections.unmodifiableList(parameter_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parameter_ = parameter_;
      } else {
        result.parameter_ = parameterBuilder_.build();
      }
    }

    private void buildPartial0(net.explorviz.code.proto.MethodData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.returnType_ = returnType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        modifier_.makeImmutable();
        result.modifier_ = modifier_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        outgoingMethodCalls_.makeImmutable();
        result.outgoingMethodCalls_ = outgoingMethodCalls_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isConstructor_ = isConstructor_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        annotation_.makeImmutable();
        result.annotation_ = annotation_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.metric_ = internalGetMetric();
        result.metric_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.explorviz.code.proto.MethodData) {
        return mergeFrom((net.explorviz.code.proto.MethodData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.explorviz.code.proto.MethodData other) {
      if (other == net.explorviz.code.proto.MethodData.getDefaultInstance()) return this;
      if (!other.getReturnType().isEmpty()) {
        returnType_ = other.returnType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.modifier_.isEmpty()) {
        if (modifier_.isEmpty()) {
          modifier_ = other.modifier_;
          bitField0_ |= 0x00000002;
        } else {
          ensureModifierIsMutable();
          modifier_.addAll(other.modifier_);
        }
        onChanged();
      }
      if (parameterBuilder_ == null) {
        if (!other.parameter_.isEmpty()) {
          if (parameter_.isEmpty()) {
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParameterIsMutable();
            parameter_.addAll(other.parameter_);
          }
          onChanged();
        }
      } else {
        if (!other.parameter_.isEmpty()) {
          if (parameterBuilder_.isEmpty()) {
            parameterBuilder_.dispose();
            parameterBuilder_ = null;
            parameter_ = other.parameter_;
            bitField0_ = (bitField0_ & ~0x00000004);
            parameterBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getParameterFieldBuilder() : null;
          } else {
            parameterBuilder_.addAllMessages(other.parameter_);
          }
        }
      }
      if (!other.outgoingMethodCalls_.isEmpty()) {
        if (outgoingMethodCalls_.isEmpty()) {
          outgoingMethodCalls_ = other.outgoingMethodCalls_;
          bitField0_ |= 0x00000008;
        } else {
          ensureOutgoingMethodCallsIsMutable();
          outgoingMethodCalls_.addAll(other.outgoingMethodCalls_);
        }
        onChanged();
      }
      if (other.getIsConstructor() != false) {
        setIsConstructor(other.getIsConstructor());
      }
      if (!other.annotation_.isEmpty()) {
        if (annotation_.isEmpty()) {
          annotation_ = other.annotation_;
          bitField0_ |= 0x00000020;
        } else {
          ensureAnnotationIsMutable();
          annotation_.addAll(other.annotation_);
        }
        onChanged();
      }
      internalGetMutableMetric().mergeFrom(
          other.internalGetMetric());
      bitField0_ |= 0x00000040;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              returnType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureModifierIsMutable();
              modifier_.add(s);
              break;
            } // case 18
            case 26: {
              net.explorviz.code.proto.ParameterData m =
                  input.readMessage(
                      net.explorviz.code.proto.ParameterData.parser(),
                      extensionRegistry);
              if (parameterBuilder_ == null) {
                ensureParameterIsMutable();
                parameter_.add(m);
              } else {
                parameterBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOutgoingMethodCallsIsMutable();
              outgoingMethodCalls_.add(s);
              break;
            } // case 34
            case 40: {
              isConstructor_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAnnotationIsMutable();
              annotation_.add(s);
              break;
            } // case 50
            case 58: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metric__ = input.readMessage(
                  MetricDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetric().getMutableMap().put(
                  metric__.getKey(), metric__.getValue());
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object returnType_ = "";
    /**
     * <code>string returnType = 1;</code>
     * @return The returnType.
     */
    public java.lang.String getReturnType() {
      java.lang.Object ref = returnType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        returnType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string returnType = 1;</code>
     * @return The bytes for returnType.
     */
    public com.google.protobuf.ByteString
        getReturnTypeBytes() {
      java.lang.Object ref = returnType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string returnType = 1;</code>
     * @param value The returnType to set.
     * @return This builder for chaining.
     */
    public Builder setReturnType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      returnType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string returnType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReturnType() {
      returnType_ = getDefaultInstance().getReturnType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string returnType = 1;</code>
     * @param value The bytes for returnType to set.
     * @return This builder for chaining.
     */
    public Builder setReturnTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      returnType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList modifier_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureModifierIsMutable() {
      if (!modifier_.isModifiable()) {
        modifier_ = new com.google.protobuf.LazyStringArrayList(modifier_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @return A list containing the modifier.
     */
    public com.google.protobuf.ProtocolStringList
        getModifierList() {
      modifier_.makeImmutable();
      return modifier_;
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @return The count of modifier.
     */
    public int getModifierCount() {
      return modifier_.size();
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @param index The index of the element to return.
     * @return The modifier at the given index.
     */
    public java.lang.String getModifier(int index) {
      return modifier_.get(index);
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the modifier at the given index.
     */
    public com.google.protobuf.ByteString
        getModifierBytes(int index) {
      return modifier_.getByteString(index);
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @param index The index to set the value at.
     * @param value The modifier to set.
     * @return This builder for chaining.
     */
    public Builder setModifier(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureModifierIsMutable();
      modifier_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @param value The modifier to add.
     * @return This builder for chaining.
     */
    public Builder addModifier(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureModifierIsMutable();
      modifier_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @param values The modifier to add.
     * @return This builder for chaining.
     */
    public Builder addAllModifier(
        java.lang.Iterable<java.lang.String> values) {
      ensureModifierIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, modifier_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModifier() {
      modifier_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string modifier = 2;</code>
     * @param value The bytes of the modifier to add.
     * @return This builder for chaining.
     */
    public Builder addModifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureModifierIsMutable();
      modifier_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<net.explorviz.code.proto.ParameterData> parameter_ =
      java.util.Collections.emptyList();
    private void ensureParameterIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        parameter_ = new java.util.ArrayList<net.explorviz.code.proto.ParameterData>(parameter_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.explorviz.code.proto.ParameterData, net.explorviz.code.proto.ParameterData.Builder, net.explorviz.code.proto.ParameterDataOrBuilder> parameterBuilder_;

    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public java.util.List<net.explorviz.code.proto.ParameterData> getParameterList() {
      if (parameterBuilder_ == null) {
        return java.util.Collections.unmodifiableList(parameter_);
      } else {
        return parameterBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public int getParameterCount() {
      if (parameterBuilder_ == null) {
        return parameter_.size();
      } else {
        return parameterBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public net.explorviz.code.proto.ParameterData getParameter(int index) {
      if (parameterBuilder_ == null) {
        return parameter_.get(index);
      } else {
        return parameterBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder setParameter(
        int index, net.explorviz.code.proto.ParameterData value) {
      if (parameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParameterIsMutable();
        parameter_.set(index, value);
        onChanged();
      } else {
        parameterBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder setParameter(
        int index, net.explorviz.code.proto.ParameterData.Builder builderForValue) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.set(index, builderForValue.build());
        onChanged();
      } else {
        parameterBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder addParameter(net.explorviz.code.proto.ParameterData value) {
      if (parameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParameterIsMutable();
        parameter_.add(value);
        onChanged();
      } else {
        parameterBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder addParameter(
        int index, net.explorviz.code.proto.ParameterData value) {
      if (parameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureParameterIsMutable();
        parameter_.add(index, value);
        onChanged();
      } else {
        parameterBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder addParameter(
        net.explorviz.code.proto.ParameterData.Builder builderForValue) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.add(builderForValue.build());
        onChanged();
      } else {
        parameterBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder addParameter(
        int index, net.explorviz.code.proto.ParameterData.Builder builderForValue) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.add(index, builderForValue.build());
        onChanged();
      } else {
        parameterBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder addAllParameter(
        java.lang.Iterable<? extends net.explorviz.code.proto.ParameterData> values) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parameter_);
        onChanged();
      } else {
        parameterBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder clearParameter() {
      if (parameterBuilder_ == null) {
        parameter_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        parameterBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public Builder removeParameter(int index) {
      if (parameterBuilder_ == null) {
        ensureParameterIsMutable();
        parameter_.remove(index);
        onChanged();
      } else {
        parameterBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public net.explorviz.code.proto.ParameterData.Builder getParameterBuilder(
        int index) {
      return getParameterFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public net.explorviz.code.proto.ParameterDataOrBuilder getParameterOrBuilder(
        int index) {
      if (parameterBuilder_ == null) {
        return parameter_.get(index);  } else {
        return parameterBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public java.util.List<? extends net.explorviz.code.proto.ParameterDataOrBuilder> 
         getParameterOrBuilderList() {
      if (parameterBuilder_ != null) {
        return parameterBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(parameter_);
      }
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public net.explorviz.code.proto.ParameterData.Builder addParameterBuilder() {
      return getParameterFieldBuilder().addBuilder(
          net.explorviz.code.proto.ParameterData.getDefaultInstance());
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public net.explorviz.code.proto.ParameterData.Builder addParameterBuilder(
        int index) {
      return getParameterFieldBuilder().addBuilder(
          index, net.explorviz.code.proto.ParameterData.getDefaultInstance());
    }
    /**
     * <code>repeated .ParameterData parameter = 3;</code>
     */
    public java.util.List<net.explorviz.code.proto.ParameterData.Builder> 
         getParameterBuilderList() {
      return getParameterFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.explorviz.code.proto.ParameterData, net.explorviz.code.proto.ParameterData.Builder, net.explorviz.code.proto.ParameterDataOrBuilder> 
        getParameterFieldBuilder() {
      if (parameterBuilder_ == null) {
        parameterBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.explorviz.code.proto.ParameterData, net.explorviz.code.proto.ParameterData.Builder, net.explorviz.code.proto.ParameterDataOrBuilder>(
                parameter_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        parameter_ = null;
      }
      return parameterBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList outgoingMethodCalls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOutgoingMethodCallsIsMutable() {
      if (!outgoingMethodCalls_.isModifiable()) {
        outgoingMethodCalls_ = new com.google.protobuf.LazyStringArrayList(outgoingMethodCalls_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @return A list containing the outgoingMethodCalls.
     */
    public com.google.protobuf.ProtocolStringList
        getOutgoingMethodCallsList() {
      outgoingMethodCalls_.makeImmutable();
      return outgoingMethodCalls_;
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @return The count of outgoingMethodCalls.
     */
    public int getOutgoingMethodCallsCount() {
      return outgoingMethodCalls_.size();
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @param index The index of the element to return.
     * @return The outgoingMethodCalls at the given index.
     */
    public java.lang.String getOutgoingMethodCalls(int index) {
      return outgoingMethodCalls_.get(index);
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the outgoingMethodCalls at the given index.
     */
    public com.google.protobuf.ByteString
        getOutgoingMethodCallsBytes(int index) {
      return outgoingMethodCalls_.getByteString(index);
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @param index The index to set the value at.
     * @param value The outgoingMethodCalls to set.
     * @return This builder for chaining.
     */
    public Builder setOutgoingMethodCalls(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutgoingMethodCallsIsMutable();
      outgoingMethodCalls_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @param value The outgoingMethodCalls to add.
     * @return This builder for chaining.
     */
    public Builder addOutgoingMethodCalls(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOutgoingMethodCallsIsMutable();
      outgoingMethodCalls_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @param values The outgoingMethodCalls to add.
     * @return This builder for chaining.
     */
    public Builder addAllOutgoingMethodCalls(
        java.lang.Iterable<java.lang.String> values) {
      ensureOutgoingMethodCallsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, outgoingMethodCalls_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutgoingMethodCalls() {
      outgoingMethodCalls_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string outgoingMethodCalls = 4;</code>
     * @param value The bytes of the outgoingMethodCalls to add.
     * @return This builder for chaining.
     */
    public Builder addOutgoingMethodCallsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOutgoingMethodCallsIsMutable();
      outgoingMethodCalls_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean isConstructor_ ;
    /**
     * <code>bool isConstructor = 5;</code>
     * @return The isConstructor.
     */
    @java.lang.Override
    public boolean getIsConstructor() {
      return isConstructor_;
    }
    /**
     * <code>bool isConstructor = 5;</code>
     * @param value The isConstructor to set.
     * @return This builder for chaining.
     */
    public Builder setIsConstructor(boolean value) {

      isConstructor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool isConstructor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsConstructor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      isConstructor_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList annotation_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAnnotationIsMutable() {
      if (!annotation_.isModifiable()) {
        annotation_ = new com.google.protobuf.LazyStringArrayList(annotation_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @return A list containing the annotation.
     */
    public com.google.protobuf.ProtocolStringList
        getAnnotationList() {
      annotation_.makeImmutable();
      return annotation_;
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @return The count of annotation.
     */
    public int getAnnotationCount() {
      return annotation_.size();
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @param index The index of the element to return.
     * @return The annotation at the given index.
     */
    public java.lang.String getAnnotation(int index) {
      return annotation_.get(index);
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the annotation at the given index.
     */
    public com.google.protobuf.ByteString
        getAnnotationBytes(int index) {
      return annotation_.getByteString(index);
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @param index The index to set the value at.
     * @param value The annotation to set.
     * @return This builder for chaining.
     */
    public Builder setAnnotation(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAnnotationIsMutable();
      annotation_.set(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @param value The annotation to add.
     * @return This builder for chaining.
     */
    public Builder addAnnotation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureAnnotationIsMutable();
      annotation_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @param values The annotation to add.
     * @return This builder for chaining.
     */
    public Builder addAllAnnotation(
        java.lang.Iterable<java.lang.String> values) {
      ensureAnnotationIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, annotation_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAnnotation() {
      annotation_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string annotation = 6;</code>
     * @param value The bytes of the annotation to add.
     * @return This builder for chaining.
     */
    public Builder addAnnotationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureAnnotationIsMutable();
      annotation_.add(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metric_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetric() {
      if (metric_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetricDefaultEntryHolder.defaultEntry);
      }
      return metric_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetric() {
      if (metric_ == null) {
        metric_ = com.google.protobuf.MapField.newMapField(
            MetricDefaultEntryHolder.defaultEntry);
      }
      if (!metric_.isMutable()) {
        metric_ = metric_.copy();
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return metric_;
    }
    public int getMetricCount() {
      return internalGetMetric().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    @java.lang.Override
    public boolean containsMetric(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetric().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetricMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetric() {
      return getMetricMap();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetricMap() {
      return internalGetMetric().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetricOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetric().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    @java.lang.Override
    public java.lang.String getMetricOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetric().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetric() {
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableMetric().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    public Builder removeMetric(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetric().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetric() {
      bitField0_ |= 0x00000040;
      return internalGetMutableMetric().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    public Builder putMetric(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetric().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metric = 7;</code>
     */
    public Builder putAllMetric(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetric().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000040;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MethodData)
  }

  // @@protoc_insertion_point(class_scope:MethodData)
  private static final net.explorviz.code.proto.MethodData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.explorviz.code.proto.MethodData();
  }

  public static net.explorviz.code.proto.MethodData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MethodData>
      PARSER = new com.google.protobuf.AbstractParser<MethodData>() {
    @java.lang.Override
    public MethodData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MethodData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MethodData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.explorviz.code.proto.MethodData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

